image: docker:latest

services:
  - docker:27.3.1

stages:
  - test

before_script:
  - docker compose pull
  - docker compose up -d

test:
  stage: test
  script:
    - docker compose exec app ./vendor/bin/phpunit --color
